on:
  push:
    branches:
      - master
      






jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

      - name: 'login to docker hub'
        run: docker login --username ${{ secrets.DOCKER_USERNAME2 }} --password ${{ secrets.DOCKER_TOKEN2 }}

      - name: 'building docker image'
        run: docker build -t ${{ secrets.DOCKER_USERNAME2 }}/myimage1_sw2 .

      - name: 'pushing to docker hub'
        run: docker push ${{ secrets.DOCKER_USERNAME2 }}/myimage1_sw2
  
